name: Publish Deb to Github

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build deb
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: deb-build:latest
      - name: a test
        run: docker images

